insert into genero (descricao) values ('Platform games');
insert into genero (descricao) values ('Shooter games');
insert into genero (descricao) values ('Fighting games');
insert into genero (descricao) values ('Beat em up games');
insert into genero (descricao) values ('Stealth game');
insert into genero (descricao) values ('Survival games');
insert into genero (descricao) values ('Rhythm games');
insert into genero (descricao) values ('Survival horror');
insert into genero (descricao) values ('Metroidvania');
insert into genero (descricao) values ('Text adventures');
insert into genero (descricao) values ('Graphic adventures');
insert into genero (descricao) values ('Visual novels');
insert into genero (descricao) values ('Interactive movie');
insert into genero (descricao) values ('Real-time 3D adventures');
insert into genero (descricao) values ('Action RPG');
insert into genero (descricao) values ('MMORPG');
insert into genero (descricao) values ('Roguelikes');
insert into genero (descricao) values ('Tactical RPG');
insert into genero (descricao) values ('Sandbox RPG');
insert into genero (descricao) values ('First-person party-based RPG');
insert into genero (descricao) values ('Cultural differences');
insert into genero (descricao) values ('Choices');
insert into genero (descricao) values ('Fantasy');
insert into genero (descricao) values ('Construction and management simulation');
insert into genero (descricao) values ('Life simulation');
insert into genero (descricao) values ('Vehicle simulation');
insert into genero (descricao) values ('4X game');
insert into genero (descricao) values ('Artillery game');
insert into genero (descricao) values ('Real-time strategy (RTS)');
insert into genero (descricao) values ('Real-time tactics (RTT)');
insert into genero (descricao) values ('Multiplayer online battle arena (MOBA)');
insert into genero (descricao) values ('Tower defense');
insert into genero (descricao) values ('Turn-based strategy (TBS)');
insert into genero (descricao) values ('Turn-based tactics (TBT)');
insert into genero (descricao) values ('Wargame');
insert into genero (descricao) values ('Grand strategy wargame');
insert into genero (descricao) values ('Racing');
insert into genero (descricao) values ('Sports game');
insert into genero (descricao) values ('Competitive');
insert into genero (descricao) values ('Sports-based fighting');
insert into genero (descricao) values ('MMO');
insert into genero (descricao) values ('Casual games');
insert into genero (descricao) values ('Party game');
insert into genero (descricao) values ('Programming game');
insert into genero (descricao) values ('Logic game');
insert into genero (descricao) values ('Trivia game');
insert into genero (descricao) values ('Board game / Card game');
insert into genero (descricao) values ('Advergame');
insert into genero (descricao) values ('Art game');
insert into genero (descricao) values ('Casual game');
insert into genero (descricao) values ('Christian game');
insert into genero (descricao) values ('Educational game');
insert into genero (descricao) values ('Electronic sports');
insert into genero (descricao) values ('Exergame');
insert into genero (descricao) values ('Personalized game');
insert into genero (descricao) values ('Serious game');
